// Copyright (C) 2016-2017 Elias Kosunen
// This file is distributed under the 3-Clause BSD License
// See LICENSE for details

// code.va

module code;

import more;

def puts(s: string) -> bool;

def func(s: string) -> string;

def main() -> int {
    var str = "test";
    let str2 = func(str);
    let str3 = func("test2");
    let str4 = func("åäö");

    puts(str);
    puts(str2);
    puts(str3);
    puts(str4);

    str = str2;

    return morefunc(2);
}
