// Copyright (C) 2016-2017 Elias Kosunen
// This file is distributed under the 3-Clause BSD License
// See LICENSE for details

// 08_for.va
// For-statement

module test_08_for;

def count() -> i32;

def main() -> i32 {
    let mut a = 1;
    for let mut i = 1, i <= count(), i += 1 {
        for (let mut j = 1, j <= 5, j += 1) {
            a *= 2;
        }
        a += 1;
    }
    return a;
}
